In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split

In [2]:
ds = pd.read_csv('./mushrooms.csv')
ds.head()

type cap_shape cap_surface cap_color bruises odor gill_attachment  \
0    p         x           s         n       t    p               f   
1    e         x           s         y       t    a               f   
2    e         b           s         w       t    l               f   
3    p         x           y         w       t    p               f   
4    e         x           s         g       f    n               f   

  gill_spacing gill_size gill_color   ...   stalk_surface_below_ring  \
0            c         n          k   ...                          s   
1            c         b          k   ...                          s   
2            c         b          n   ...                          s   
3            c         n          n   ...                          s   
4            w         b          k   ...                          s   

  stalk_color_above_ring stalk_color_below_ring veil_type veil_color  \
0                      w                      w         p          w   
1                      w                      w         p          w   
2                      w                      w         p          w   
3                      w                      w         p          w   
4                      w                      w         p          w   

  ring_number ring_type spore_print_color population habitat  
0           o         p                 k          s       u  
1           o         p                 n          n       g  
2           o         p                 n          n       m  
3           o         p                 k          s       u  
4           o         e                 n          a       g  

[5 rows x 23 columns]

In [3]:
le = LabelEncoder()
df = ds.apply(le.fit_transform)
df.head()

type  cap_shape  cap_surface  cap_color  bruises  odor  gill_attachment  \
0     1          5            2          4        1     6                1   
1     0          5            2          9        1     0                1   
2     0          0            2          8        1     3                1   
3     1          5            3          8        1     6                1   
4     0          5            2          3        0     5                1   

   gill_spacing  gill_size  gill_color   ...     stalk_surface_below_ring  \
0             0          1           4   ...                            2   
1             0          0           4   ...                            2   
2             0          0           5   ...                            2   
3             0          1           5   ...                            2   
4             1          0           4   ...                            2   

   stalk_color_above_ring  stalk_color_below_ring  veil_type  veil_color  \
0                       7                       7          0           2   
1                       7                       7          0           2   
2                       7                       7          0           2   
3                       7                       7          0           2   
4                       7                       7          0           2   

   ring_number  ring_type  spore_print_color  population  habitat  
0            1          4                  2           3        5  
1            1          4                  3           2        1  
2            1          4                  3           2        3  
3            1          4                  2           3        5  
4            1          0                  3           0        1  

[5 rows x 23 columns]

In [4]:
data = df.values
data = np.array(data)
np.random.shuffle(data)
print data

[[1 5 0 ... 1 5 1]
 [1 2 2 ... 1 4 1]
 [0 2 3 ... 3 5 0]
 ...
 [0 5 0 ... 2 5 0]
 [0 5 3 ... 3 4 0]
 [0 5 3 ... 2 5 0]]


In [5]:
x = data[:200,1:]
y = data[:200,0]
y[y==0]=-1
print(x.shape)
print(y.shape)
print x
print y

(200, 22)
(200,)
[[5 0 3 ... 1 5 1]
 [2 2 8 ... 1 4 1]
 [2 3 2 ... 3 5 0]
 ...
 [5 3 3 ... 3 5 0]
 [2 3 2 ... 3 5 0]
 [5 2 4 ... 7 4 2]]
[ 1  1 -1  1  1 -1  1  1  1 -1 -1 -1  1  1  1 -1 -1  1 -1  1  1 -1  1 -1
 -1 -1 -1 -1 -1  1 -1 -1 -1  1 -1  1 -1  1 -1  1  1 -1  1  1  1  1 -1  1
  1  1  1 -1 -1 -1 -1 -1  1  1 -1 -1 -1 -1 -1  1 -1 -1 -1  1 -1 -1  1  1
 -1 -1 -1 -1  1 -1  1 -1 -1  1  1  1  1  1  1 -1  1  1 -1  1  1 -1 -1 -1
 -1 -1 -1 -1 -1  1 -1  1  1  1  1  1  1 -1  1  1 -1  1 -1  1 -1 -1  1  1
  1  1 -1  1  1 -1  1 -1 -1 -1 -1  1 -1  1  1  1 -1  1  1 -1  1 -1  1 -1
 -1 -1  1 -1 -1  1  1  1 -1 -1  1  1  1  1  1 -1  1 -1 -1  1 -1  1  1 -1
 -1  1  1 -1 -1 -1 -1 -1 -1  1 -1  1  1 -1 -1  1  1 -1 -1 -1 -1  1  1  1
 -1 -1 -1 -1  1 -1 -1  1]


In [6]:
x_train, x_test, y_train, y_test = train_test_split(x,y,test_size=0.2)

In [7]:
print(x_train.shape)
print(x_test.shape)
print(y_train.shape)
print(y_test.shape)

(160, 22)
(40, 22)
(160,)
(40,)


In [8]:
def hypothesis(w, x, b):
    return np.dot(w,x.T)+b
res = hypothesis(np.random.random((22,)),x_train,0)
print res.shape
print res
print y_train

(160,)
[29.17932973 14.95653904 27.06153035 26.74755518 28.24345304 27.5119835
 31.15674736 35.58646938 24.78906985 28.23721213 31.25469552 21.84821947
 29.43515244 27.26960882 35.380517   26.61378203 29.88459246 27.85208033
 33.9739707  27.19064026 22.14167519 17.46399206 24.68682831 21.5973594
 24.78679304 25.27508783 20.45430837 30.43451652 28.52954047 25.0324704
 28.96778418 22.83428967 16.98523871 27.35287135 27.64954509 26.67766637
 26.33433252 28.8824952  24.84948522 27.24486841 26.57869514 27.29164257
 27.69592533 23.96470398 25.4090157  30.76045811 20.67476383 25.32048365
 19.24534487 26.07365838 29.91911841 28.4773347  20.55161885 25.72695873
 25.1023979  30.23391945 22.45779943 23.41439623 21.73861504 25.00616048
 30.01222503 29.97751072 30.26646635 25.70840108 25.23155367 32.54685853
 26.59820205 25.14856838 27.22977483 26.06341839 36.09558759 22.6806452
 27.10594724 29.70600104 26.07169055 15.2468249  29.27907519 28.79731832
 25.34284642 28.78238042 16.67415903 31.32260949

In [9]:
def hingeLoss(w, x, b, y):
        loss = 0
        ## |w|^2 = w * w.T
        loss += 0.5*np.dot(w,w.T)
        ti = np.multiply(y,hypothesis(w,x,b))
        print ti.shape
#         print ti
        ti = 1-ti
#         print ti
        ## only keeping ti>0
        ti = ti[ti>0]
#         print ti
        loss += np.sum(ti)
        return loss
print hingeLoss(np.random.random((22,)),x_train,10,y_train)

(160,)
3274.751329679784


In [64]:
def fit(x, y, learning_rate=0.001,n_epochs=500):
    n_features = x.shape[1]
    n_samples = x.shape[0]
    w = np.random.random((n_features,))
    b = 0.0
    c = 1.0
    losses = []
    for epoch in range(n_epochs):
        l = hingeLoss(w, x, b, y)
        print l
        losses.append(l)
        gradw = np.zeros((n_features,))
        gradb = 0
        ti = np.multiply(y, hypothesis(w, x, b))
        for ix in range(n_features):
            for jx in range(ti.shape[0]):
                if ti[jx]>1:
                    gradw[ix] += 0
                    gradb += 0
                else:
                    gradw[ix] += c*x[jx][ix]*y[jx]
                    gradb += c*y[jx]
        w = w - learning_rate*w + learning_rate*gradw
        b = b + learning_rate*gradb        
    return w,b
wf,bf = fit(x_train,y_train)

2468.0720236924226
691.5075107059757
901.838677962617
269.0024069178047
951.2147262057515
156.52580428267154
529.4619665257457
560.715089557909
770.8099430456597
197.3324694650919
529.5007496433403
394.3429975859839
675.4411491976381
198.05909999646616
289.87303362283546
158.71138555558431
193.08636277878188
225.14356823131757
568.4698132150164
241.24753466172274
470.61008123362984
246.22951263069228
398.22787634452095
144.62459152805883
146.49590463413193
149.39463823149907
182.65897296812156
185.8609473301308
368.18092849255515
245.72867502685082
460.72098171789236
211.62982962279617
334.9586781292774
128.66092399213295
126.17269481304612
131.9853351865207
150.77582319176568
147.3066571991895
290.40313235497086
161.95314120054948
292.08129591015387
147.29319264677417
258.1092209224262
144.82891153660591
241.77403970126483
150.8218991146355
266.9809099895638
156.09655614641818
269.3230140905584
142.6449124400521
237.4882862942499
133.29023155158254
180.51094791963675
122.0661727771726

80.86736687564743
83.58112936174669
77.36593181238511
76.57241252684486
76.85660761035341
75.14474957657676
73.76540454354033
72.45615266550712
70.94331783976318
69.3040234950724
68.30752965775969
67.55168241648497
66.70380319444179
65.53788638137962
65.23264349313324
64.20575517665424
63.5846543720561
63.13302557468058
62.882891464361755
63.987010241242
66.9976754674201
71.14740181198005
143.39079873626108
356.49469391621875
649.6368125223707
103.62888023009947
163.30459940982539
137.015163124645
275.3176907911558
208.76805653909955
415.7704598007882
158.19699221059278
237.70123185539308
86.25964698289597
87.74876854228638
81.43618419353935
85.06945163086704
77.49826723630687
83.02861962852938
75.70695270159848
78.970133631874
72.10954042627043
70.64328447218237
69.62854252252248
68.61578506401996
67.60500812967697
66.59620776042576
65.63123597612889
64.89184311495973
64.11608637163967


In [65]:
def accuracy(x,y):
    hx = hypothesis(wf, x, bf)
    hx[hx>=0]=1
    hx[hx<0]=-1
    print float(hx[hx==y].shape[0])/y.shape[0]
accuracy(x_test,y_test)

0.9


In [10]:
from sklearn.svm import SVC

In [11]:
clf = SVC()
clf.fit(x_train,y_train)
clf.score(x_test,y_test)

0.975

In [13]:
class SVM:
    def __init__(self,c=1.0):
        self.c = c
        self.w = np.random.random((x.shape[1]))
        self.b = 0
    def hypothesis(self, w, x, b):
        return np.dot(w,x.T)+b
    def hingeLoss(self, w, x, b, y):
        loss = 0
        loss += 0.5*np.multiply(w,w.T)
        ti = np.multiply(y,hypothesis(w,x,b))
        ti = 1-ti
        ti[ti<=0]=0
        loss += np.sum(ti)
        return loss
    def fit(self,x, y, batch_size=100, learning_rate=0.001,n_epochs=100):
        n_features = x.shape[1]
        n_samples = x.shape[0]
        self.c = 1.0
        losses = []
        for epoch in range(n_epochs):
            l = self.hingeLoss(self.w, x, self.b, y)
            print l
            losses.append(l)
            for b1 in range(0,n_samples,batch_size):
                x1 = x[b1:b1+batch_size]
                y1 = y[b1:b1+batch_size]
                gradw = np.zeros((n_features,))
                gradb = 0
                ti = np.multiply(y1, self.hypothesis(self.w, x1, self.b))
#             print ti
                for ix in range(n_features):
                    for jx in range(ti.shape[0]):
                        if ti[jx]>=1:
                            gradw[ix] += 0
                            gradb += 0
                        else:
                            gradw[ix] += self.c*x1[jx][ix]*y1[jx]
                            gradb += self.c*y1[jx]
#             print gradw
#             print gradb
                self.w = self.w - learning_rate*self.w + learning_rate*gradw
                self.b = self.b + learning_rate*gradb        
#             print w,b
    def accuracy(self,x,y):
        hx = hypothesis(self.w, x, self.b)
        hx[hx>=0]=1
        hx[hx<0]=-1
        return float(hx[hx==y].shape[0])/y.shape[0]

In [20]:
svm = SVM(c=10.0)

In [21]:
svm.fit(x_train,y_train,n_epochs=500)

[2721.17885498 2721.5102589  2721.44364241 2721.22811866 2721.20300873
 2721.33505583 2721.17598734 2721.17429658 2721.39645813 2721.60445708
 2721.17825897 2721.32246516 2721.47539015 2721.54774165 2721.47195733
 2721.3827839  2721.39724113 2721.21884459 2721.2559004  2721.59625524
 2721.18267122 2721.23495404]
[937.28491408 937.49507166 937.32369581 937.29760901 937.26896938
 937.37912555 937.26160658 937.26094763 937.26402814 937.64018798
 937.2610636  937.33715151 937.44923381 937.32368873 937.29379395
 937.46881135 937.38724231 937.28214405 937.27039748 937.47414463
 937.27359324 937.29262759]
[181.54204554 181.67432807 181.49494837 181.50550442 181.52200269
 181.57895152 181.47722298 181.4773125  181.50894046 181.83181426
 181.48252268 181.52472263 181.61783995 181.48343243 181.47689298
 181.6842105  181.56984856 181.49028169 181.4766832  181.61692498
 181.51776081 181.49962847]
[169.11627863 169.26189737 169.07963766 169.08669183 169.10456573
 169.16674778 169.06154384 169.06236

[69.86948656 70.05875136 69.87353736 69.8792934  69.94391255 70.01253368
 69.87089962 69.92562131 70.01389596 70.0419646  69.92747696 69.86935084
 69.88368232 69.87017779 69.8791376  70.05488944 70.0593276  69.88722542
 69.90378103 69.86998011 70.11465477 69.9023092 ]
[65.68162318 65.86619416 65.68436629 65.69198314 65.76056954 65.82489817
 65.68281676 65.73928968 65.79816287 65.84906576 65.7418653  65.68124382
 65.69417265 65.68244712 65.69124723 65.86601572 65.87290236 65.69921017
 65.71344872 65.68130758 65.93328867 65.71007556]
[63.96631097 64.1449916  63.96732436 63.97719046 64.05274528 64.10921584
 63.96716474 64.02546984 64.06134319 64.12873122 64.02737265 63.96565964
 63.97737654 63.96710949 63.97555807 64.14963206 64.15773277 63.9834933
 63.99666587 63.96560856 64.21948946 63.99128572]
[102.18360425 102.35984268 102.18181717 102.19437857 102.25841634
 102.328563   102.18336161 102.24559349 102.27404844 102.34366273
 102.24574611 102.18178116 102.19394342 102.18192386 102.18651

[56.50545106 56.61426761 56.50306678 56.57096682 56.57817735 56.64617417
 56.50659693 56.69334136 56.62236266 56.57853873 56.66763815 56.52430917
 56.50367907 56.50092182 56.50185508 56.66479591 56.7099663  56.516569
 56.58989005 56.50519588 56.8678706  56.51791228]
[54.66588487 54.77190523 54.66222068 54.73151002 54.74593934 54.80604634
 54.66723853 54.8555064  54.7643537  54.7367273  54.83030899 54.68531634
 54.66442244 54.66139401 54.66257836 54.82459102 54.86958745 54.67678086
 54.74418475 54.66824997 55.02516628 54.67615984]
[55.42306222 55.52743685 55.41851053 55.48850535 55.51175777 55.56237544
 55.42433593 55.61412861 55.50434358 55.49140709 55.58827247 55.44278084
 55.42155087 55.41834094 55.41942497 55.58084175 55.62566877 55.43344854
 55.49516074 55.42822236 55.78149754 55.43117769]
[97.06738645 97.1755136  97.06177642 97.13265705 97.14459419 97.20834825
 97.06784196 97.26485908 97.14852594 97.13442806 97.23439937 97.08554657
 97.06437643 97.06319176 97.06156559 97.22350094 

[48.1369691  48.22083988 48.14653012 48.26001456 48.22376401 48.27526116
 48.17288824 48.60275364 48.23447902 48.14871273 48.60445784 48.20307711
 48.16367365 48.13841362 48.13933804 48.26580242 48.34472751 48.15032571
 48.22690331 48.16355594 48.45812072 48.14093907]
[42.66370654 42.74343663 42.66991073 42.78609065 42.75546643 42.80023044
 42.69958003 43.1303553  42.75035909 42.67492896 43.13301687 42.73010696
 42.6915366  42.66414919 42.66475325 42.79185539 42.86726635 42.67619445
 42.75142172 42.69583121 42.97784723 42.66543342]
[40.13275084 40.20945454 40.13664945 40.25520336 40.22207687 40.26826949
 40.16854226 40.60146188 40.20593828 40.14383944 40.60218352 40.19894862
 40.16124587 40.13318152 40.13348156 40.26044934 40.33428678 40.14493386
 40.21686295 40.16981177 40.44569991 40.13343781]
[37.47295768 37.5475295  37.47571974 37.59553635 37.55953049 37.60805403
 37.50872537 37.944759   37.53217296 37.4839723  37.94160263 37.5382871
 37.50169908 37.47369299 37.4737627  37.60026564

[45.6299049  45.7061529  45.64090596 45.75783568 45.6929112  45.76749214
 45.68658671 46.21587441 45.70841651 45.63160674 46.22057292 45.70694065
 45.66244111 45.63127137 45.6341477  45.74309892 45.84072599 45.64318366
 45.71988064 45.67571101 45.92079136 45.63070405]
[43.77750137 43.85170069 43.78968218 43.90421979 43.84550044 43.91487485
 43.83410088 44.36418432 43.84699629 43.77873606 44.36777396 43.85481943
 43.81022639 43.77825053 43.78115101 43.89004955 43.98794732 43.79070206
 43.86522131 43.82696201 44.06250796 43.777896  ]
[42.17146501 42.24361859 42.18487527 42.29695375 42.24462529 42.30860136
 42.22795869 42.75883688 42.23245724 42.17222669 42.76131921 42.24904246
 42.20435683 42.17162409 42.17451599 42.28334576 42.38151285 42.18456445
 42.25693358 42.22470147 42.45063557 42.1714488 ]
[41.97199651 42.04324451 41.9852865  42.09623888 42.04422238 42.10887251
 42.02836097 42.56220627 42.02868237 41.97245343 42.56467483 42.04901732
 42.00451127 41.9718184  41.97488903 42.0831883

[38.23069408 38.30584616 38.2356982  38.36153252 38.28169199 38.36756743
 38.31917607 38.98944884 38.28306834 38.22924543 38.94959143 38.31831947
 38.26838387 38.23091899 38.23640502 38.32500168 38.4440065  38.24225635
 38.3219914  38.31052245 38.49066596 38.22875752]
[43.48169922 43.55630468 43.48940369 43.61073255 43.5355212  43.61883045
 43.56999796 44.24210153 43.52814929 43.48010071 44.1986522  43.56829293
 43.51869962 43.48223136 43.48829255 43.57537625 43.69588722 43.49329308
 43.56979829 43.5625654  43.73681209 43.47954477]
[76.70389004 76.78385629 76.71694596 76.83482254 76.7469814  76.84454125
 76.79399344 77.47451377 76.75776198 76.70314465 77.42603321 76.79058781
 76.74023134 76.70817822 76.71676278 76.79807378 76.92540638 76.71733333
 76.79853058 76.77056307 76.96757888 76.70301679]
[41.19945048 41.27618447 41.20822922 41.33238236 41.24730219 41.33530627
 41.29137679 41.97607146 41.2886217  41.19691688 41.94562638 41.29178644
 41.23743433 41.19831774 41.20476452 41.2911286

[39.43358875 39.49293933 39.44414211 39.55969761 39.46232992 39.5724125
 39.57063178 40.43921383 39.48665488 39.44213365 40.29469316 39.52360496
 39.47574393 39.43188561 39.43998398 39.50271953 39.655546   39.4428699
 39.5412059  39.55074619 39.62315307 39.42820343]
[35.38463031 35.44144032 35.39303709 35.50884393 35.4150368  35.52202622
 35.52131508 36.38820334 35.43422187 35.39277169 36.24666206 35.47471786
 35.42666523 35.38076702 35.38791804 35.45260731 35.60416195 35.39299828
 35.48997958 35.50745091 35.56701108 35.37828288]
[32.97582763 33.03028946 32.98144482 33.09988448 33.00726695 33.11301414
 33.11230478 33.98141177 33.0153737  32.98444657 33.83212259 33.06589376
 33.01865721 32.97231991 32.97862225 33.04387196 33.19415275 32.98415888
 33.07734945 33.10884214 33.15782432 32.96967113]
[33.10546973 33.15987811 33.11001478 33.22937764 33.13627975 33.2434996
 33.2422566  34.11500081 33.1387573  33.1152544  33.95526968 33.19472167
 33.14867109 33.10320856 33.10965266 33.17409764 3

[55.66819326 55.7262173  55.67423637 55.78856077 55.68396363 55.81237134
 55.8282708  56.79396359 55.70681772 55.68684327 56.57234086 55.75614924
 55.70976933 55.66895472 55.68088422 55.72872427 55.90028441 55.68004484
 55.77187037 55.80237311 55.82904634 55.66345706]
[49.77962216 49.83974067 49.78747664 49.9023265  49.79371692 49.92413581
 49.94290155 50.91425587 49.83734076 49.79887769 50.69750152 49.87005466
 49.82143889 49.78052929 49.79172136 49.83971848 50.01269073 49.7914217
 49.89411448 49.90678824 49.94027046 49.77542815]
[48.43345687 48.49496721 48.44208149 48.55749587 48.44537236 48.57830078
 48.5993767  49.57545291 48.5084418  48.4528788  49.3610463  48.52507115
 48.47520552 48.43462593 48.44627327 48.49311604 48.66749568 48.44520049
 48.55722961 48.55379571 48.59274036 48.42998475]
[39.22518271 39.2838313  39.23119169 39.34595732 39.24079344 39.36664947
 39.39169922 40.36036291 39.2983817  39.24361699 40.15224177 39.31637308
 39.26635428 39.22120827 39.23226849 39.28234437

[30.40526885 30.45971766 30.4067178  30.52915766 30.4220886  30.54765124
 30.59243028 31.66618476 30.4397512  30.4389563  31.35840639 30.49905651
 30.45389049 30.40569614 30.41077786 30.4581978  30.63204556 30.4156039
 30.5191285  30.58952496 30.54770195 30.40175596]
[37.01083795 37.06563531 37.01389924 37.132249   37.02690735 37.15381195
 37.19739856 38.27419786 37.04064669 37.04419461 37.96106072 37.10201574
 37.05750033 37.01203354 37.01806953 37.0630854  37.23965507 37.02117954
 37.11991242 37.19082058 37.1517141  37.00675568]
[73.00810944 73.0684141  73.01733446 73.13205019 73.01860143 73.15585298
 73.19728967 74.28388108 73.04501223 73.04256573 73.96292605 73.09955039
 73.05418571 73.0150974  73.02247967 73.06165905 73.24649656 73.02116088
 73.1240193  73.16596198 73.15927275 73.00496773]
[37.53786616 37.59574269 37.543174   37.66465077 37.55100292 37.68011835
 37.72924624 38.82771327 37.61977957 37.57112272 38.52459721 37.63452273
 37.58494556 37.53741362 37.54424494 37.58792372

[32.7699488  32.82987816 32.77071715 32.892482   32.78754959 32.9145026
 32.98071153 34.16996661 32.79914261 32.82015252 33.76912671 32.8673311
 32.82139058 32.77014719 32.77916834 32.81601165 33.00054177 32.78129139
 32.88197022 32.95933165 32.89775999 32.76676849]
[74.09927932 74.16593063 74.10551863 74.22381578 74.11032334 74.24913655
 74.31265486 75.51197284 74.13351486 74.150116   75.10158999 74.19596472
 74.14937493 74.10550988 74.11702845 74.14664931 74.34082629 74.11349493
 74.21619675 74.2641958  74.23908212 74.09699074]
[36.37275579 36.43685807 36.37455117 36.5005015  36.38723584 36.51641809
 36.58845748 37.79999527 36.45383516 36.42293116 37.4090203  36.47562268
 36.42451118 36.37121984 36.38098739 36.41651676 36.60373143 36.38242886
 36.51243375 36.52442685 36.49871972 36.3670364 ]
[34.03478163 34.09878084 34.03591732 34.1615135  34.04972623 34.17894157
 34.25014593 35.46191864 34.10022625 34.08528106 35.06454684 34.13683361
 34.08685476 34.03405835 34.04367518 34.07889261 

[31.50586664 31.56415728 31.5080067  31.62549933 31.51536634 31.65061714
 31.74033732 33.01903943 31.55495049 31.56671974 32.56168603 31.6061153
 31.55921169 31.50283877 31.51139197 31.54342882 31.73775433 31.51427108
 31.63904801 31.69756717 31.61511543 31.49976026]
[31.01258581 31.07030672 31.01454373 31.13233271 31.02260729 31.15839896
 31.24721118 32.5295154  31.05242813 31.07465425 32.05657263 31.11214813
 31.0664658  31.01154891 31.01980925 31.05108982 31.24532818 31.02187648
 31.13904221 31.21479062 31.12441967 31.0080628 ]
[30.91017819 30.96746551 30.91229297 31.0277462  30.92101768 31.05575504
 31.14435049 32.42607133 30.94272906 30.97252599 31.95266502 31.00822
 30.96363295 30.90875799 30.91685716 30.94832182 31.14248264 30.91939807
 31.03184646 31.11588146 31.01944845 30.90559737]
[34.16756871 34.2238731  34.17103191 34.28242434 34.1788888  34.31290831
 34.40073617 35.68361931 34.19519651 34.22964334 35.20655724 34.26354694
 34.21936139 34.16586919 34.17491805 34.20480021 34

[76.57158837 76.63577732 76.58033521 76.68289714 76.57598134 76.72533337
 76.82969008 78.20278789 76.60353974 76.64534159 77.66634855 76.66789263
 76.6243647  76.57589417 76.58867181 76.60485731 76.82028657 76.58326474
 76.69901078 76.76581723 76.67760537 76.56704049]
[37.68450123 37.74234518 37.68402905 37.79781671 37.69048695 37.82892533
 37.94348492 39.32737816 37.76753468 37.75618658 38.8203426  37.78704411
 37.73866337 37.6776004  37.68741285 37.71226774 37.91772773 37.68933887
 37.83860982 37.86564626 37.77378631 37.67424748]
[33.54629117 33.60668701 33.54549357 33.66120193 33.5515374  33.69273847
 33.80628684 35.19191625 33.61303424 33.61933307 34.6706044  33.64952791
 33.60228623 33.54207358 33.55206131 33.57599315 33.78202228 33.55315516
 33.69504173 33.7381389  33.64313722 33.53841493]
[31.78717103 31.84782569 31.78655181 31.9023669  31.79250811 31.93427092
 32.04809721 33.43472643 31.84196791 31.86156197 32.90073691 31.88982605
 31.84382482 31.78496448 31.79449271 31.8179924

[41.84782732 41.90772189 41.85321398 41.96114814 41.84834599 41.99901838
 42.12986343 43.60778321 41.92086713 41.93834247 42.97236192 41.94931822
 41.90451557 41.85021295 41.86258895 41.87449978 42.09074313 41.8564632
 41.99112814 42.05740405 41.93812794 41.84115851]
[32.82100541 32.87522021 32.82229947 32.93251024 32.82227782 32.96806707
 33.10158025 34.57583635 32.88756235 32.91107388 33.94820117 32.92350878
 32.87885108 32.8181432  32.82722749 32.84571978 33.05619888 32.8270636
 32.96516671 33.044599   32.90220189 32.81276926]
[30.34892081 30.40151595 30.3477246  30.45949433 30.35061371 30.49539844
 30.62837649 32.10237241 30.40228289 30.43863132 31.47160774 30.45101559
 30.40726627 30.34565467 30.35411044 30.37353869 30.58248422 30.35461761
 30.48812399 30.58471653 30.43022419 30.34177011]
[28.93300725 28.98593594 28.93154474 29.04305924 28.9351593  29.08034761
 29.21223753 30.68784716 28.97536829 29.02325051 30.04610351 29.03418213
 28.99164692 28.931282   28.93973942 28.95841831 

[30.94247125 30.99275859 30.93999361 31.04879649 30.93969864 31.08903454
 31.24182452 32.79541005 30.99598586 31.04425763 32.10135522 31.04589095
 31.00260674 30.93654732 30.94454275 30.96133359 31.17632763 30.94622731
 31.09187891 31.18153634 31.01587817 30.93318292]
[29.08959044 29.13968805 29.08730525 29.19640403 29.0878558  29.23752146
 29.38914119 30.94616428 29.13337662 29.19283705 30.23610343 29.19256802
 29.15050625 29.08608503 29.09368769 29.10977132 29.32460411 29.0945576
 29.23199606 29.3404979  29.16574141 29.0824453 ]
[28.72575806 28.77725992 28.72350261 28.83210208 28.72458723 28.87457375
 29.02502691 30.58354917 28.76071108 28.82998006 29.86405708 28.82782664
 28.78697273 28.72339546 28.7307565  28.74677363 28.9614482  28.731621
 28.86306686 28.98381641 28.80293671 28.72036219]
[31.72153719 31.77327617 31.72028661 31.82530274 31.720837   31.87063033
 32.02014052 33.57744487 31.74881857 31.82603733 32.85502008 31.82107715
 31.78151102 31.7194832  31.72709018 31.7422172  3

In [22]:
svm.accuracy(x_test,y_test)

1.0

In [23]:
svm1 = SVM(c=0.0)

In [25]:
svm1.fit(x_train,y_train,n_epochs=500)

[2626.80473615 2626.7930448  2627.03394162 2626.89908167 2627.22376174
 2626.82443121 2626.79993008 2627.24774261 2627.09216822 2627.00140193
 2626.970977   2626.81338587 2626.82656997 2626.79637261 2627.12652751
 2627.29129673 2626.95720032 2626.79513548 2627.16439499 2626.96135546
 2627.05755182 2626.81267423]
[843.08186778 843.07271791 843.11781504 843.14954724 843.22150917
 843.08283298 843.07307999 843.51576425 843.08619563 843.2421432
 843.17581438 843.06925537 843.07292694 843.15555385 843.11387907
 843.56483511 843.15159587 843.06808758 843.246129   843.11795421
 843.16036376 843.07344317]
[224.312849   224.28129038 224.29652204 224.34393419 224.36062227
 224.28483067 224.27733895 224.73003038 224.28288401 224.4354847
 224.3537931  224.27357811 224.2743611  224.44315736 224.28344739
 224.7684494  224.33881428 224.27462579 224.38302364 224.3080713
 224.33109171 224.27851445]
[152.32941791 152.2872041  152.29896236 152.34253258 152.3338485
 152.292411   152.284195   152.75636849 

[100.7260984  100.80977927 100.74780824 100.73258418 100.77486025
 100.75857327 100.72941651 101.61874575 100.85583637 100.74922365
 100.78774069 100.83406626 100.7897115  100.72724303 100.72652094
 101.11740786 100.88113399 100.7251165  100.7422629  100.72535367
 101.20408861 100.73169997]
[57.07821891 57.16060348 57.09534997 57.08714812 57.13770205 57.11009753
 57.08356959 57.97773172 57.26750146 57.1003793  57.15325136 57.19777395
 57.14961852 57.08475422 57.07820166 57.46902491 57.22656253 57.07822035
 57.10448447 57.07837816 57.52851675 57.08619287]
[54.53972526 54.61895915 54.54961141 54.54915306 54.60069453 54.57096579
 54.54515022 55.44234005 54.70564257 54.56137058 54.6191608  54.66075678
 54.61388267 54.54857882 54.53978258 54.9289621  54.68530042 54.53969898
 54.56497196 54.53969288 54.98726781 54.54413185]
[51.29647876 51.37365402 51.30207102 51.30598925 51.35600786 51.32743681
 51.30183006 52.20204625 51.43726474 51.31767358 51.37906221 51.41687459
 51.37173256 51.30595833

 39.39656936 39.36968295 39.70938492 39.34368938]
[37.08974828 37.18614835 37.0995083  37.1143906  37.14248908 37.12943383
 37.12964134 38.21627204 37.1573971  37.08945031 37.41936635 37.24352998
 37.18517279 37.08997732 37.09106251 37.39302597 37.2530121  37.09026967
 37.13970665 37.11831666 37.45299628 37.08930879]
[39.95159846 40.04792241 39.9606536  39.97600647 39.99966631 39.99200199
 39.99164081 41.07993156 40.00568526 39.95159316 40.28020812 40.10176869
 40.04564544 39.95184247 39.9537241  40.25397376 40.11681145 39.95256379
 39.99793708 39.98108584 40.31711899 39.95145092]
[95.31078835 95.41493842 95.32635488 95.33546562 95.34746698 95.35377942
 95.3516696  96.44980769 95.36643569 95.31096571 95.63983727 95.45614897
 95.40031444 95.31105356 95.31803332 95.61210259 95.48540548 95.31236174
 95.35707635 95.33137674 95.69669943 95.31103685]
[42.92860934 43.03065936 42.9408057  42.9553509  42.97528883 42.96918759
 42.97142823 44.07891573 43.03394909 42.92784777 43.28108091 43.085760

[64.11900439 64.214151   64.13398029 64.14865551 64.15490626 64.16781753
 64.19415439 65.4020893  64.16336626 64.12182163 64.61610854 64.26587998
 64.21054534 64.11829172 64.12567754 64.36681085 64.30328231 64.12064355
 64.18504687 64.17155717 64.43024822 64.11718233]
[44.50120437 44.5956385  44.51684266 44.53197694 44.53696687 44.54903783
 44.5780246  45.79281648 44.57086315 44.50381238 45.0105631  44.65272593
 44.59417483 44.49928301 44.50606592 44.74722874 44.68337532 44.50196397
 44.57844002 44.55044969 44.80420898 44.49895995]
[44.6970599  44.7919237  44.71407724 44.72718147 44.73610437 44.7448157
 44.77464405 45.98781145 44.76400433 44.6996531  45.207885   44.8474392
 44.78912332 44.69444709 44.70188184 44.9415751  44.87981665 44.69745734
 44.77185963 44.74883199 44.99759084 44.69444966]
[49.67495837 49.77175943 49.69363875 49.70529895 49.71333414 49.72357059
 49.75392589 50.9686808  49.74357064 49.67794858 50.18989312 49.82480864
 49.76585832 49.67247537 49.68130208 49.91858017 

[32.66072706 32.74020797 32.66564457 32.69732717 32.68653209 32.7164305
 32.78963923 34.13928035 32.71133531 32.68188063 33.35525716 32.79955989
 32.75264085 32.6583537  32.66621107 32.85054686 32.85281036 32.66196294
 32.75968114 32.76575941 32.89790786 32.657424  ]
[37.65324871 37.7325507  37.66061522 37.68829422 37.68040205 37.70949698
 37.78188484 39.13078145 37.69421035 37.67449252 38.34353587 37.78964988
 37.7432069  37.65092643 37.65929323 37.8420348  37.84743643 37.6545214
 37.74527597 37.76039188 37.88992209 37.64972513]
[64.34250188 64.42753769 64.35560302 64.37931482 64.36285918 64.4016995
 64.47375315 65.83070656 64.3934734  64.36449653 65.03814521 64.47835106
 64.43142512 64.34376346 64.35474312 64.53159788 64.54397906 64.34549421
 64.44053487 64.43568246 64.58844042 64.33932979]
[43.97089019 44.05624435 43.98345895 44.00851092 43.99075204 44.02881342
 44.10474091 45.46766379 44.04803898 43.99311318 44.68287044 44.11098167
 44.06098428 43.9701169  43.98001593 44.15818451 4

[31.9426282  32.01782738 31.94813658 31.97942478 31.96197546 32.00423504
 32.10176749 33.50963833 31.98028849 31.97794901 32.72052515 32.07559824
 32.03240227 31.93849925 31.94612413 32.10543003 32.14441718 31.94415493
 32.05000611 32.08280809 32.13979413 31.93743078]
[62.29506292 62.37729742 62.30641152 62.33302434 62.31024308 62.36062229
 62.45631772 63.86983545 62.33069932 62.331559   63.07268593 62.42544121
 62.38218737 62.29459503 62.30606874 62.45881877 62.50610931 62.29906258
 62.4007696  62.42361467 62.50468595 62.29101911]
[40.95035602 41.03111912 40.96195547 40.98964806 40.96548692 41.01449999
 41.11384276 42.53546662 41.0129273  40.98726486 41.74376178 41.08531375
 41.03852809 40.94792378 40.95881834 41.11229495 41.15877561 40.95305273
 41.07193204 41.07159345 41.15285975 40.94498966]
[36.48132305 36.56080753 36.49192205 36.5194912  36.49943556 36.5442505
 36.64551665 38.06270304 36.5452498  36.51858026 37.27815341 36.61635661
 36.56946777 36.47684397 36.48782127 36.64165003

[29.66030575 29.73017055 29.66210395 29.69928633 29.6783712  29.72832023
 29.84461169 31.33608734 29.68976591 29.71327464 30.52439359 29.79079515
 29.74794229 29.65642105 29.66579058 29.80081586 29.86807594 29.66397362
 29.76977268 29.82159855 29.82154918 29.655992  ]
[35.19560834 35.26598152 35.19827779 35.2341383  35.21189616 35.26451071
 35.37979614 36.8738635  35.22467722 35.24870923 36.05360403 35.32453408
 35.28117758 35.19250336 35.20341637 35.33556103 35.40583525 35.19967689
 35.30272218 35.35394748 35.35565928 35.19095525]
[57.87610492 57.95213575 57.88408088 57.91656051 57.88717544 57.94825543
 58.06321006 59.56537512 57.91483092 57.92983816 58.7397199  58.00465874
 57.96081344 57.87643803 57.89023106 58.01668796 58.09397479 57.882195
 57.98971042 58.01720419 58.04429915 57.87198369]
[44.66429891 44.74098928 44.67337604 44.70604144 44.6742975  44.73589929
 44.85433674 46.3627371  44.72509349 44.71886226 45.54226514 44.79632732
 44.74968257 44.66360698 44.67678817 44.80365881 

[36.01389126 36.0862297  36.02260605 36.05635866 36.02443603 36.08899583
 36.2262053  37.78181465 36.08283827 36.08269871 36.95025135 36.14518883
 36.0994066  36.01014155 36.0216601  36.13504441 36.23350916 36.01854499
 36.14811695 36.18156538 36.15012611 36.00708293]
[32.06618333 32.13527907 32.07064684 32.10757651 32.07760939 32.13999357
 32.27771713 33.83209872 32.12269946 32.13451168 33.00231569 32.19636281
 32.15248623 32.06106047 32.0712028  32.18626048 32.28232634 32.06977813
 32.19506936 32.24518697 32.20022485 32.05915598]
[31.27119523 31.34045239 31.27469674 31.31262727 31.2820689  31.3463426
 31.48270873 33.03840678 31.3154771  31.34007552 32.20030149 31.39959366
 31.35711628 31.26726665 31.27749815 31.39161802 31.48930851 31.27574952
 31.39421082 31.45644488 31.40873397 31.26552701]
[29.4270956  29.49507866 29.42953037 29.46751942 29.43882818 29.50171893
 29.63819621 31.1926662  29.46421041 29.49625001 30.35771706 29.55475074
 29.51330309 29.42235324 29.43175538 29.54681111

 31.44522236 31.53578012 31.44304617 31.32544311]
[57.3490351  57.4215138  57.35417178 57.39028841 57.35559185 57.43104971
 57.57984351 59.20349699 57.37443198 57.43062388 58.32894767 57.47083522
 57.43222943 57.34919165 57.36195248 57.45497227 57.57551818 57.35558774
 57.46303816 57.54077905 57.46882587 57.34383438]
[49.07379593 49.14760926 49.08117466 49.11721409 49.07999984 49.15596636
 49.30772153 50.94711827 49.12727836 49.15509957 50.07150824 49.19939619
 49.1566948  49.07411388 49.08790544 49.17852035 49.30203767 49.07969727
 49.20477549 49.24434969 49.19590574 49.06702648]
[39.1302831  39.20259881 39.13609265 39.17358252 39.13605275 39.2109161
 39.3662265  41.006542   39.19970022 39.21172449 40.13695162 39.25724954
 39.21331942 39.12835308 39.14153517 39.233372   39.35573866 39.13478741
 39.27017341 39.30009093 39.24620679 39.12213806]
[32.37568107 32.44296563 32.37628922 32.41794432 32.38339768 32.45355345
 32.61019498 34.24907953 32.43559804 32.45688378 33.38425123 32.5030363

[84.63681814 84.70134646 84.64231646 84.68399359 84.63518135 84.72936638
 84.90728981 86.65728421 84.66507021 84.74516471 85.68303622 84.75853522
 84.71659193 84.64163946 84.65492873 84.72098928 84.87292827 84.64526164
 84.76516669 84.85248082 84.7378053  84.63265205]
[41.33591233 41.39024103 41.32829511 41.38150454 41.33361487 41.4167951
 41.60613391 43.36512106 41.42071796 41.44124771 42.43215682 41.46528124
 41.41813794 41.32550985 41.33419069 41.4123709  41.55075569 41.33518284
 41.49372393 41.53995503 41.41625012 41.3239705 ]
[32.14312185 32.20423147 32.13880536 32.19254865 32.14352286 32.22865146
 32.41669003 34.18203204 32.20777648 32.25268299 33.2268236  32.27459397
 32.22826517 32.13733245 32.14552406 32.2229488  32.36482571 32.14622304
 32.29479541 32.35799488 32.23561103 32.1353145 ]
[29.35754149 29.4195654  29.35457955 29.40833487 29.35877827 29.44506787
 29.63192048 31.40031994 29.41035155 29.46905538 30.42998762 29.48776219
 29.44295591 29.35500557 29.36323908 29.43895381

[40.06806534 40.1269654  40.07338798 40.11777264 40.06249909 40.1634353
 40.37134567 42.20671341 40.12525441 40.19957289 41.20262518 40.18822977
 40.15160689 40.06663577 40.07793352 40.13248032 40.30170048 40.07326315
 40.2222068  40.29881049 40.14106925 40.05951504]
[34.8866084  34.94469662 34.89113683 34.93482239 34.88164789 34.98065118
 35.19088432 37.01783595 34.94079132 35.01929198 36.0232121  35.00787915
 34.97014811 34.88241124 34.89324876 34.94981437 35.11768136 34.89083589
 35.03802406 35.12805321 34.95519    34.8770855 ]
[29.45224284 29.50690974 29.45197727 29.49926195 29.44766666 29.54400159
 29.75509113 31.58015606 29.49625503 29.58446031 30.58934234 29.57304856
 29.53704964 29.44540143 29.45459521 29.51419405 29.67794533 29.45478972
 29.59978655 29.70824581 29.5168137  29.44282545]
[27.38387308 27.43718024 27.38132765 27.43065941 27.3796077  27.47555944
 27.68580464 29.51184327 27.41853805 27.51585558 28.51369775 27.50397785
 27.46907133 27.37726559 27.38603044 27.44587049

In [26]:
svm1.accuracy(x_test,y_test)

0.975