In [1]:
import numpy as np
import pandas as pd
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split

In [2]:
df = pd.read_csv('./mushrooms.csv')
df.head()

type cap_shape cap_surface cap_color bruises odor gill_attachment  \
0    p         x           s         n       t    p               f   
1    e         x           s         y       t    a               f   
2    e         b           s         w       t    l               f   
3    p         x           y         w       t    p               f   
4    e         x           s         g       f    n               f   

  gill_spacing gill_size gill_color   ...   stalk_surface_below_ring  \
0            c         n          k   ...                          s   
1            c         b          k   ...                          s   
2            c         b          n   ...                          s   
3            c         n          n   ...                          s   
4            w         b          k   ...                          s   

  stalk_color_above_ring stalk_color_below_ring veil_type veil_color  \
0                      w                      w         p          w   
1                      w                      w         p          w   
2                      w                      w         p          w   
3                      w                      w         p          w   
4                      w                      w         p          w   

  ring_number ring_type spore_print_color population habitat  
0           o         p                 k          s       u  
1           o         p                 n          n       g  
2           o         p                 n          n       m  
3           o         p                 k          s       u  
4           o         e                 n          a       g  

[5 rows x 23 columns]

In [3]:
le = LabelEncoder()
ds = df.apply(le.fit_transform)

In [4]:
ds.head()

type  cap_shape  cap_surface  cap_color  bruises  odor  gill_attachment  \
0     1          5            2          4        1     6                1   
1     0          5            2          9        1     0                1   
2     0          0            2          8        1     3                1   
3     1          5            3          8        1     6                1   
4     0          5            2          3        0     5                1   

   gill_spacing  gill_size  gill_color   ...     stalk_surface_below_ring  \
0             0          1           4   ...                            2   
1             0          0           4   ...                            2   
2             0          0           5   ...                            2   
3             0          1           5   ...                            2   
4             1          0           4   ...                            2   

   stalk_color_above_ring  stalk_color_below_ring  veil_type  veil_color  \
0                       7                       7          0           2   
1                       7                       7          0           2   
2                       7                       7          0           2   
3                       7                       7          0           2   
4                       7                       7          0           2   

   ring_number  ring_type  spore_print_color  population  habitat  
0            1          4                  2           3        5  
1            1          4                  3           2        1  
2            1          4                  3           2        3  
3            1          4                  2           3        5  
4            1          0                  3           0        1  

[5 rows x 23 columns]

In [5]:
data = ds.values
print(data)

[[1 5 2 ... 2 3 5]
 [0 5 2 ... 3 2 1]
 [0 0 2 ... 3 2 3]
 ...
 [0 2 2 ... 0 1 2]
 [1 3 3 ... 7 4 2]
 [0 5 2 ... 4 1 2]]


In [6]:
data_y = data[:,0]
data_x = data[:,1:]
print(data_x.shape)
print(data_y.shape)

(8124, 22)
(8124,)


In [7]:
x_train,x_test,y_train,y_test = train_test_split(data_x,data_y,test_size=0.2)

In [8]:
print(x_train.shape)
print(x_test.shape)
print(y_train.shape)
print(y_test.shape)

(6499, 22)
(1625, 22)
(6499,)
(1625,)


In [9]:
def prior_prob(x_train,y_train,label_value):
    n_rows = x_train[y_train==label_value]
    prob_val = n_rows.shape[0]/float(x_train.shape[0])
    return prob_val
prior_prob(x_train,y_train,1)

0.4820741652561933

In [10]:
def cond_prob(x_train,y_train,feature_col,feature_val,label_value):
    n_rows = x_train[y_train==label_value]
    constraint_rows = n_rows[n_rows[:,feature_col]==feature_val]
    prob_value = constraint_rows.shape[0]/float(n_rows.shape[0])
    return prob_value

In [11]:
classes = np.unique(y_train)
print classes

[0 1]


In [12]:
preds = []
for ix in range(x_test.shape[0]):
    post_prob = []
    for jx in classes:
        likelihood = 1.0
#         print(x_test[ix])
        for kx in x_test[ix]:
            cond = cond_prob(x_train,y_train,kx,x_test[ix,kx],jx)
            likelihood *= cond
        prior = prior_prob(x_train,y_train,jx)
        posterior_prob = likelihood*prior
#         print(posterior_prob)
        post_prob.append(posterior_prob)
    post_prob = np.array(post_prob)
#     print(post_prob)
    pred_label = post_prob.argmax()
    preds.append(pred_label)

In [13]:
y_test = np.array(y_test)
preds = np.array(preds)
accuracy = np.sum(np.array(y_test==preds))/float(y_test.shape[0])

In [14]:
print(accuracy)

0.9372307692307692
